<?php
#Activty log variables. When a user goes to a book or photo album, that is logged
#when they hit the next button on a story the view is logged.
#NB - Please note that what follows is simply the contents of the bm_actions table
#     and needs to be synchronized with it.
#     It should be dynamically generated when the actions table is altered
#     by a php script that generates the config_actions.php.
#     Alternatively the variables could be generated by a user lookup

$ACTION_LOGIN_CODE = 1;
$ACTION_LOGIN = 'Log-in';

$ACTION_LOGIN_FAILURE_CODE = 2;
$ACTION_LOGIN_FAILURE = 'Log-in failure';

?>